AppMou/config/routes.rb
AppMou::Application.routes.draw do
resources :users do
	resources :posts
end

  root :to => 'users#index'

end

AppMou/app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :description
end

AppMou/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :user_name, :email, :roll_no, :age, :dept
  validates :user_name, :presence => true
  has_many :posts , :dependent => :destroy
  before_validation :ensure_name_has_a_value
  protected
  def ensure_name_has_a_value
  if user_name.nil?
  self.user_name = email unless email.blank?
  end
end
  before_create do |user|
  user.user_name = user.user_name.capitalize
  end
end

AppMou/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

AppMou/app/controllers/posts_controller.rb
class PostsController < ApplicationController

def new
@post=Post.new
end

def create
user=User.find(params[:user_id])
post=user.posts.create(params[:post])
redirect_to user_path(user)
end

def show
@user = User.find(params[:user_id])
@post= @user.posts.find(params[:id])
end

def index
@user =User.find(params[:user_id])
@posts=@user.posts.find(:all)

end

def edit
@user=User.find(params[:user_id])
@post=@user.posts.find(params[:id])
end

def update
@user=User.find(params[:user_id])
@post=@user.posts.find(params[:id])
@post.update_attributes(params[:post])
@post.save!
redirect_to user_post_path(@user)
end

def destroy
@user = User.find(params[:user_id])
@post= @user.posts.find(params[:id])
@post.destroy
redirect_to user_posts_path(@user)
end

end

AppMou/app/controllers/users_controller.rb
class UsersController < ApplicationController
def index
	@users=User.all
end
def new
	@user=User.new
end
def create
  @user=User.create(params[:user])
if @user.save
 UserMailer.welcome_email(@user).deliver
else
 render :action=>'create'
end
 redirect_to users_path
end  
def show
  @user=User.find(params[:id])
end
def edit
  @user=User.find(params[:id])
end
def update
user=User.find(params[:id])
user.update_attributes(params[:user])
user.save!
redirect_to users_path
end
def destroy
 user=User.find(params[:id])
 @posts=Post.where(:user_id=>user.id)
 @posts.each do |post|
   post.destroy
  end
 user.destroy
 redirect_to users_path
end
end

AppMou/app/helpers/application_helper.rb
module ApplicationHelper
end

AppMou/app/helpers/posts_helper.rb
module PostsHelper
end

AppMou/app/helpers/users_helper.rb
module UsersHelper
end

AppMou/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Rails Application</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="font-family:Trebuchet MS;text-align:center;background-color:#FF6347;">
<%= render :partial => 'shared/head' %>
<%= yield %>
<%= render :partial => 'shared/foot' %>
</body>
</html>

AppMou/app/views/posts/edit.html.erb
<html>
<%=form_for @posts,:url=>user_post_path do |f|%>
<h2><%=f.label :title%>
<%=f.text_field :title%></h2>
<h2><%=f.label :description%>
<%=f.text_field :description%></h2>
<%= f.submit%>
<%end%>

</html>

AppMou/app/views/posts/index.html.erb
<h1>SHOW POST</h1>
<%@posts.each do |p|%>
<h3>Title:</h3><%=p.title%><br>
<h3>Description:</h3><%=p.description%><br>
<%= link_to "show",user_post_path(@user,p)%>
<hr>
<%end%>

AppMou/app/views/posts/new.html.erb
<html>
<%=form_for @post,:url=>user_posts_path do |f|%>
<h2><%=f.label :title%>
<%=f.text_field :title%></h2>
<h2><%=f.label :description%>
<%=f.text_field :description%></h2>
<%= f.submit%>
<%end%>

</html>

AppMou/app/views/posts/show.html.erb
<html>
<%@posts.each do |p|%>
Title:<%=p.title%><br>
Description:<%=p.description%><br>
<%=link_to "edit post",edit_user_post_path(p)%>
<%=link_to "delete post",user_post_path(p),:method=>:delete%>
<hr>
<%end%>
</html>

AppMou/app/views/shared/_foot.html.erb
<hr>
<H2 style="font-size:30px;text-align:center;color:Blue">Created by Moumita</H2>

AppMou/app/views/shared/_head.html.erb
<H1 style="font-size:30px;text-align:center;text-decoration:underline;color:Blue">MY APP</H1>
<hr>

AppMou/app/views/users/_menu.html.erb
<html>
<%=form_for @user do |f|%>
<h2><%=f.label :name%>
<%=f.text_field :name%></h2>
<h2><%=f.label :email%>
<%=f.text_field :email%></h2>
<h2><%=f.label :dept%>
<%=f.text_field :dept%></h2>
<h2><%=f.label :roll_no%>
<%=f.text_field :roll_no%></h2>
<h2><%=f.label :age%>
<%=f.text_field :age%></h2>
<%=f.submit%>
<%end%>
</html>

AppMou/app/views/users/edit.html.erb
<%= render :partial => "menu" %>

AppMou/app/views/users/index.html.erb
<html>
 
<%@users.each do |u|%>
<p style="font-size:20px;text-align:center;word-spacing:10px;">
 <%=u.user_name%>;
 <%=u.email%>
<%=link_to "show User",user_path(u)%>
</p>
<%end%>
<%=link_to "create User",new_user_path%>
</html>

AppMou/app/views/users/new.html.erb
<%= render :partial => "menu" %>

AppMou/app/views/users/show.html.erb
<html>

<h3>Name:<%= @user.user_name %></h3>
<h3>Email:<%= @user.email%></h3>
<h3>Roll:<%= @user.roll_no%></h3>
<h3>Dept:<%= @user.dept%></h3>
<h3>Age:<%= @user.age%></h3>
<p style="font-size:20px;text-align:center;word-spacing:10px;">
<%=link_to "edit User", edit_user_path(@user)%>
<%=link_to "delete User", user_path(@user), :method=>:delete %>
<%=link_to "Post", new_user_post_path(@user) %>
<%=link_to "show post",user_posts_path(@user)%><hr></p>
</html>